language: ruby
before_script: cd spec/dummy; bundle exec rake db:migrate RAILS_ENV=test
script: bundle exec rspec
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
gemfile:
  - gemfiles/rails.3.0.x.gemfile
  - gemfiles/rails.3.1.x.gemfile
  - Gemfile
